name: HIQ SBOM

on: 
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hiq

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Generate SBOM
      run: |
        pip install cyclonedx-bom
        python -m cyclonedx_py -e --format json -o hiq-sbom.cdx.json
    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: hiq-sbom.cdx.json
        path: ./hiq/hiq-sbom.cdx.json
        if-no-files-found: error
