name: HIQ SBOM

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hiq

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Generate SBOM using venv
      run: |
        sbom_venv_generation.sh
    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: hiq-sbom.cdx.json
        path: ./hiq/hiq-sbom.cdx.json
        if-no-files-found: error
